package net.royalur.model.dice;

import net.royalur.name.Name;
import net.royalur.name.Named;

import javax.annotation.Nonnull;
import java.util.random.RandomGenerator;

/**
 * A generator of dice rolls.
 * @param <R> The type of rolls generated by this dice.
 */
public abstract class Dice<R extends Roll> implements Named<Name> {

    /**
     * The name of this dice.
     */
    private final @Nonnull Name name;

    /**
     * The source of randomness used to generate dice rolls.
     */
    private final @Nonnull RandomGenerator random;

    /**
     * Instantiates this dice with {@code random} as the source
     * of randomness to generate dice rolls.
     * @param name The name of this dice.
     * @param random The source of randomness used to generate dice rolls.
     */
    public Dice(@Nonnull Name name, @Nonnull RandomGenerator random) {
        this.name = name;
        this.random = random;
    }

    @Override
    public @Nonnull Name getName() {
        return name;
    }

    /**
     * Gets the source of randomness that is used to generate dice rolls.
     * @return The source of randomness that is used to generate dice rolls.
     */
    public @Nonnull RandomGenerator getRandom() {
        return random;
    }

    /**
     * Gets the maximum value that could be rolled by this dice.
     * @return The maximum value that this dice could possibly roll.
     */
    public abstract int getMaxRollValue();

    /**
     * Generates a random roll using this dice, and returns just the value.
     * @return A random roll of this dice, and returns just the value.
     */
    public abstract int rollValue();

    /**
     * Generates a roll with value {@code value} using this dice.
     * @param value The value of the dice to be rolled.
     * @return A roll with value {@code value} of this dice.
     */
    public abstract @Nonnull R roll(int value);

    /**
     * Generates a random roll using this dice.
     * @return A random roll of this dice.
     */
    public @Nonnull R roll() {
        return roll(rollValue());
    }
}
