package net.royalur.rules;

import net.royalur.model.Roll;

import javax.annotation.Nonnull;

/**
 * A generator of dice rolls.
 * @param <R> The type of rolls generated by this dice.
 */
public interface Dice<R extends Roll> {

    /**
     * Gets the maximum value that could be rolled by this dice.
     * @return The maximum value that this dice could possibly roll.
     */
    int getMaxRollValue();

    /**
     * Gets an identifier that can be used to uniquely identify this type of dice.
     * @return An identifier that can be used to uniquely identify this type of dice.
     */
    @Nonnull String getIdentifier();

    /**
     * Generates a random roll using this dice.
     * @return A random roll of this dice.
     */
    @Nonnull R roll();

    /**
     * Generates a roll with value {@code value} using this dice.
     * @param value The value of the dice to be rolled.
     * @return A roll with value {@code value} of this dice.
     */
    @Nonnull R roll(int value);
}
