package net.royalur;

import net.royalur.agent.Agent;
import net.royalur.agent.LikelihoodAgent;
import net.royalur.agent.utility.PiecesAdvancedUtilityFn;
import net.royalur.model.PlayerState;
import net.royalur.model.dice.DiceType;
import net.royalur.model.dice.Roll;
import net.royalur.model.path.MurrayPathPair;
import net.royalur.model.path.SkiriukPathPair;
import net.royalur.rules.RuleSet;
import net.royalur.rules.standard.StandardPiece;
import net.royalur.stats.GameStats;
import net.royalur.stats.GameStatsSummary;
import net.royalur.stats.GameStatsTarget;
import net.royalur.stats.SummaryStat;

import javax.annotation.Nonnull;
import java.util.List;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * This file intends to hold tests that can be performed
 * to different sets of game rules and paths to compare them.
 */
public class RGUStatistics {

    /**
     * Instantiate to run statistics about the paths available for the Royal Game of Ur.
     */
    public RGUStatistics() {}

    /**
     * Generates statistics for a single game generated by {@code gameGenerator},
     * and played by two AI agents.
     * @param gameGenerator A generator to produce a new game for the agents to play.
     * @param agentGenerator A generator to produce the agents to play the game.
     * @return Statistics about the game that was played between two random agents.
     */
    private @Nonnull GameStats testAgentActions(
            @Nonnull Supplier<Game<StandardPiece, PlayerState, Roll>> gameGenerator,
            @Nonnull Function<
                    RuleSet<StandardPiece, PlayerState, Roll>,
                    Agent<StandardPiece, PlayerState, Roll>
            > agentGenerator
    ) {

        Game<StandardPiece, PlayerState, Roll> game = gameGenerator.get();
        Agent<StandardPiece, PlayerState, Roll> light = agentGenerator.apply(game.getRules());
        Agent<StandardPiece, PlayerState, Roll> dark = agentGenerator.apply(game.getRules());
        Agent.playAutonomously(game, light, dark);
        return GameStats.gather(game);
    }

    /**
     * Runs tests using AI agents with many game settings.
     * @param agentGenerator The generator of the agents to play each game.
     * @param tests The number of tests to run for each game setting.
     */
    public void testAgentActions(
            @Nonnull Function<
                    RuleSet<StandardPiece, PlayerState, Roll>,
                    Agent<StandardPiece, PlayerState, Roll>
            > agentGenerator,
            int tests
    ) {
        List<Supplier<Game<StandardPiece, PlayerState, Roll>>> generators = List.of(
                () -> Game.builder().finkel().build(),
                () -> Game.builder().finkel().safeRosettes(false).build(),
                () -> Game.builder().finkel().rosettesGrantExtraRolls(false).build(),
                () -> Game.builder().finkel().capturesGrantExtraRolls(true).build(),
                () -> Game.builder().masters().build(),
                () -> Game.builder().masters().capturesGrantExtraRolls(true).build(),
                () -> Game.builder().finkel().paths(new SkiriukPathPair()).build(),
                () -> Game.builder().finkel().paths(new MurrayPathPair()).build(),
                () -> Game.builder().aseb().build(),
                () -> Game.builder().finkel().dice(DiceType.THREE_BINARY_0MAX).build()
        );
        for (Supplier<Game<StandardPiece, PlayerState, Roll>> gameGenerator : generators) {
            Game<StandardPiece, PlayerState, Roll> sample = gameGenerator.get();
            String desc = sample.getBoard().getShape().getName().getTextName()
                    + ", " + sample.getRules().getPaths().getName().getTextName()
                    + ", " + sample.getRules().getDiceFactory().getName().getTextName()
                    + ", " + (sample.getRules().areRosettesSafe() ? "safe" : "unsafe")
                    + ", " + (sample.getRules().doRosettesGrantExtraRolls() ? "rosettes+" : "rosettes-")
                    + ", " + (sample.getRules().doCapturesGrantExtraRolls() ? "captures+" : "captures-");

            GameStats[] stats = new GameStats[tests];
            long start = System.nanoTime();
            for (int test = 0; test < tests; ++test) {
                stats[test] = testAgentActions(gameGenerator, agentGenerator);
            }
            long nanosPerTest = (System.nanoTime() - start) / tests;
            double msPerTest = (double) nanosPerTest / 1_000_000.0;
            String timings = String.format(" (%.2f ms/game)", msPerTest);
            GameStatsSummary summary = GameStats.summarise(stats);

            System.out.println(desc + timings + ":");
            for (GameStatsTarget target : GameStatsTarget.values()) {
                double movesMean = summary.getMovesStatistic(target, SummaryStat.MEAN);
                double movesStd = summary.getMovesStatistic(target, SummaryStat.STD_DEV);
                double rollsMean = summary.getRollsStatistic(target, SummaryStat.MEAN);
                double rollsStd = summary.getRollsStatistic(target, SummaryStat.STD_DEV);
                System.out.printf(
                        "%-15s%-19s%-19s%n",
                        target.getName() + ":",
                        ((int) movesMean) + " moves ± " + ((int) movesStd) + ",",
                        ((int) rollsMean) + " rolls ± " + ((int) rollsStd)
                );
            }
            System.out.println();
        }
    }

    /**
     * The main entrypoint to run statistics about the Royal Game of Ur board shapes and paths.
     * @param args Ignored.
     */
    public static void main(String[] args) {
        new RGUStatistics().testAgentActions(
                rules -> new LikelihoodAgent<>(new PiecesAdvancedUtilityFn(rules), 0.09f),
                1
        );
    }
}
